# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/ges_dette
#     username: root
#     password: 
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.MySQLDialect
#   profiles:
#     active: default 

# ---
# spring:
#   profiles: postgresql
#   datasource:
#     url: jdbc:postgresql://localhost:5432/sama
#     username: postgres
#     password: Taphatall01
#     driver-class-name: org.postgresql.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.PostgreSQLDialect

persistance: "MYSQLDETTES"
repository: 
  userRepository: repository.jpa.UserJpa
  clientRepository: repository.jpa.ClientJpa
  detteRepository: repository.jpa.DetteJpa
  articleRepository: repository.jpa.ArticleJpa
  paiementRepository: repository.jpa.PaimentJpa

# persistance: "sama"
# repository: 
# client : repository.postgreImpl.ClientRepositoryPostgreImpl
# user : repository.postgreImpl.UserRepositoryPostgreImpl
# dette : repository.postgreImpl.DetteRepositoryPostgreImpl
# article: repository.postgreImpl.ArticleRepositoryPostgreImpl


service:
client:  services.ClientService.java
user:  services.UserService.java
dette:  services.DetteService.java
article:  services.ArticleService.java